apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployemnt
  labels:
    app: ngnix
    tier: frontend
spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
